version: '3.5'
services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_BACKEND_APP_URL=http://localhost:8001
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
